/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scicalc;

/**
 *
 * @author Keshav Kumar Choudhary
 */
public class mainUI extends javax.swing.JFrame {
 boolean isResultPerformed=false;
    /**
     * Creates new form mainUI
     */
    public mainUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        decimalBtn = new javax.swing.JButton();
        result = new javax.swing.JButton();
        addbtn = new javax.swing.JButton();
        btnNo1 = new javax.swing.JButton();
        btnNo2 = new javax.swing.JButton();
        btnNo3 = new javax.swing.JButton();
        btnNo4 = new javax.swing.JButton();
        btnNo5 = new javax.swing.JButton();
        btnNo6 = new javax.swing.JButton();
        btnNo7 = new javax.swing.JButton();
        btnNo8 = new javax.swing.JButton();
        btnNo9 = new javax.swing.JButton();
        divbtn = new javax.swing.JButton();
        subbtn = new javax.swing.JButton();
        mulbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editTxt = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        clearbtn = new javax.swing.JButton();
        clearAllbtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setText("0");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        decimalBtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        decimalBtn.setText(".");
        decimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalBtnActionPerformed(evt);
            }
        });

        result.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        result.setText("=");
        result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addbtn.setText("+");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        btnNo1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo1.setText("1");
        btnNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo1ActionPerformed(evt);
            }
        });

        btnNo2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo2.setText("2");
        btnNo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo2ActionPerformed(evt);
            }
        });

        btnNo3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo3.setText("3");
        btnNo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo3ActionPerformed(evt);
            }
        });

        btnNo4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo4.setText("4");
        btnNo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo4ActionPerformed(evt);
            }
        });

        btnNo5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo5.setText("5");
        btnNo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo5ActionPerformed(evt);
            }
        });

        btnNo6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo6.setText("6");
        btnNo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo6ActionPerformed(evt);
            }
        });

        btnNo7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo7.setText("7");
        btnNo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo7ActionPerformed(evt);
            }
        });

        btnNo8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo8.setText("8");
        btnNo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo8ActionPerformed(evt);
            }
        });

        btnNo9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnNo9.setText("9");
        btnNo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo9ActionPerformed(evt);
            }
        });

        divbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        divbtn.setText("/");
        divbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divbtnActionPerformed(evt);
            }
        });

        subbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        subbtn.setText("-");
        subbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subbtnActionPerformed(evt);
            }
        });

        mulbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mulbtn.setText("*");
        mulbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulbtnActionPerformed(evt);
            }
        });

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        editTxt.setColumns(20);
        editTxt.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        editTxt.setRows(5);
        jScrollPane1.setViewportView(editTxt);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Calculator");

        clearbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clearbtn.setText("C");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        clearAllbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clearAllbtn.setText("CE");
        clearAllbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllbtnActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Close");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(decimalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(divbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNo6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNo7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNo8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnNo9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clearbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mulbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNo7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNo8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNo9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearAllbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNo6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mulbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(decimalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(divbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void divbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divbtnActionPerformed
        if(isResultPerformed==true)
        {
            String s;
             s=new String();
             editTxt.setText(s);
             isResultPerformed=false;
        }
        else
        {
            String s=editTxt.getText();
         
            char[] c=s.toCharArray();
            int n=c.length;
            if(n==0)
            {
                s=new String();
                editTxt.setText(s);
            } 
            else{
               s=s+"/";
                editTxt.setText(s);
            }  
        }
    }//GEN-LAST:event_divbtnActionPerformed

    private void subbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subbtnActionPerformed
      if(isResultPerformed==true){
            String s;
            s=new String();
            editTxt.setText(s);
            isResultPerformed=false;
      }
      else
      {
         String s=editTxt.getText();
         
         char[] c=s.toCharArray();
         int n=c.length;
         if(n==0)
         {
            s=new String();
            editTxt.setText(s);
         } 
         else
         {
            s=s+"-";
            editTxt.setText(s);
         }
        }
    }//GEN-LAST:event_subbtnActionPerformed

    private void mulbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulbtnActionPerformed
     if(isResultPerformed==true)
     {
         String s;
         s=new String();
         editTxt.setText(s);
         isResultPerformed=false;
     }
     else
     {
         String s=editTxt.getText();
         
         char[] c=s.toCharArray();
         int n=c.length;
         if(n==0)
         {
             s=new String();
             editTxt.setText(s);
         } 
         else
         {
             s=s+"*";
             editTxt.setText(s);
         }
        }   
    }//GEN-LAST:event_mulbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
         String s=editTxt.getText();
         
         char[] c=s.toCharArray();
         int n=c.length;
         if(n==0||n==1)
         {
             s=new String();
             editTxt.setText(s);
         }
         else
         {
             String substring = s.substring(0, s.length() - 1);
             editTxt.setText(substring);  
         }
    }//GEN-LAST:event_clearbtnActionPerformed

    private void clearAllbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllbtnActionPerformed
        isResultPerformed=false;
        String s;
        s=new String();
        editTxt.setText(s);
    }//GEN-LAST:event_clearAllbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String s=editTxt.getText();
         s=s+"0";
         editTxt.setText(s);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo1ActionPerformed
         String s=editTxt.getText();
         s=s+"1";
         editTxt.setText(s);
    }//GEN-LAST:event_btnNo1ActionPerformed

    private void btnNo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo2ActionPerformed
         String s=editTxt.getText();
         s=s+"2";
         editTxt.setText(s);
    }//GEN-LAST:event_btnNo2ActionPerformed

    private void btnNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo3ActionPerformed
         String s=editTxt.getText();
         s=s+"3";
         editTxt.setText(s);
    }//GEN-LAST:event_btnNo3ActionPerformed

    private void btnNo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo4ActionPerformed
         String s=editTxt.getText();
         s=s+"4";
         editTxt.setText(s);     
    }//GEN-LAST:event_btnNo4ActionPerformed

    private void btnNo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo5ActionPerformed
         String s=editTxt.getText();
         s=s+"5";
         editTxt.setText(s);       
    }//GEN-LAST:event_btnNo5ActionPerformed

    private void btnNo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo6ActionPerformed
         String s=editTxt.getText();
         s=s+"6";
         editTxt.setText(s);      
    }//GEN-LAST:event_btnNo6ActionPerformed

    private void btnNo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo7ActionPerformed
         String s=editTxt.getText();
         s=s+"7";
         editTxt.setText(s); 
    }//GEN-LAST:event_btnNo7ActionPerformed

    private void btnNo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo8ActionPerformed
         String s=editTxt.getText();
         s=s+"8";
         editTxt.setText(s);   
    }//GEN-LAST:event_btnNo8ActionPerformed

    private void btnNo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo9ActionPerformed
         String s=editTxt.getText();
         s=s+"9";
         editTxt.setText(s);    
    }//GEN-LAST:event_btnNo9ActionPerformed

    private void decimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalBtnActionPerformed
      String s=editTxt.getText().replace(" ","");
      
      if(s==""||s==null)
      {
           s="0.";
           editTxt.setText(s);
      }
      else if(s.contains("."))
      {
           //do nothing
      }
      else
      {
           s=s+".";
           editTxt.setText(s);   
      }
    }//GEN-LAST:event_decimalBtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        if(isResultPerformed==true)
        {
             String s;
             s=new String();
             editTxt.setText(s);
             isResultPerformed=false;
        }
        else
        {
            String s=editTxt.getText();
         
            char[] c=s.toCharArray();
            int n=c.length;
            
            if(n==0)
            {
                s=new String();
                editTxt.setText(s);
            } 
            else
            {
                s=s+"+";
                editTxt.setText(s);
            }
        }       
    }//GEN-LAST:event_addbtnActionPerformed

    private void resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultActionPerformed
            isResultPerformed=true;    
            String s=editTxt.getText().trim();
            
            int result;
            result=(int)InfixEvaluation.check(s);
            
            String neww;
            if(result==Integer.MAX_VALUE)
            {
                neww="Unhandled Error Occured!";
            }
            else
            {
                neww=""+result;
            }
            editTxt.setText(neww);
    }//GEN-LAST:event_resultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton btnNo1;
    private javax.swing.JButton btnNo2;
    private javax.swing.JButton btnNo3;
    private javax.swing.JButton btnNo4;
    private javax.swing.JButton btnNo5;
    private javax.swing.JButton btnNo6;
    private javax.swing.JButton btnNo7;
    private javax.swing.JButton btnNo8;
    private javax.swing.JButton btnNo9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearAllbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JButton decimalBtn;
    private javax.swing.JButton divbtn;
    private javax.swing.JTextArea editTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mulbtn;
    private javax.swing.JButton result;
    private javax.swing.JButton subbtn;
    // End of variables declaration//GEN-END:variables
}
